### ISSUE TITLE
Digital Eyes Marketplace address throws an error

### ISSUE THREAD

**Issue by usmankhan95** [MonkeDAO/observer#2]
No such host is known. (api.mainnet-beta.solana.com:443)

![image](https://user-images.githubusercontent.com/17094424/134574186-c611d78b-b4ea-4d18-9ab2-12a8a1ba0a1a.png)

"Digital Eyes" "A7p8451ktDCHq5yYaHczeLMYsjRsAkzc3hCXcSrwYHU7"

This was working fine just yesterday (22/09/21) but errors now

This is the address in the code, is it outdated?

**Comment by murlokito** [comment]
This is probably a DNS issue, saw someone reporting the same earlier and it is working fine on my machine.
